_wandb:
    value:
        cli_version: 0.22.3
        e:
            nrb4emt184mxavf5km3bp3ejy06um1wh:
                codePath: scripts/test_wandb.py
                codePathLocal: scripts/test_wandb.py
                email: micahmok@berkeley.edu
                executable: /Users/micah/miniconda3/envs/tpu-ols/bin/python
                git:
                    commit: 5d02f7b70cd05f559b050d81d9dc320ed1ffdf25
                    remote: https://github.com/RahulBirCodes/bluey.git
                host: wifi-10-41-156-140.wifi.berkeley.edu
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/micah/bluey/scripts/test_wandb.py
                python: CPython 3.10.19
                root: /Users/micah/bluey
                startedAt: "2025-11-07T22:05:56.848850Z"
                writerId: nrb4emt184mxavf5km3bp3ejy06um1wh
        m: []
        python_version: 3.10.19
        t:
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
